### ISSUE TITLE
Missing dependency "requests" with clean install (python 3.12)

### ISSUE THREAD

**Issue by oising** [clemensv/avrotize#2]
New machine, fresh python 3.12 + pip:

```
> pipenv install
> pip install avrotize
> avrotize
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\oisin\AppData\Local\Programs\Python\Python312\Scripts\avrotize.exe\__main__.py", line 4, in <module>
  File "C:\Users\oisin\AppData\Local\Programs\Python\Python312\Lib\site-packages\avrotize\avrotize.py", line 9, in <module>
    from avrotize.jsonstoavro import convert_jsons_to_avro
  File "C:\Users\oisin\AppData\Local\Programs\Python\Python312\Lib\site-packages\avrotize\jsonstoavro.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
After having ran "pip install requests" all looks good now.

**Comment by kschulst** [comment]
FWIW, if installing `avrotize` with pipx, like so:

```
pipx install avrotize
```

you can get by using:

```
pipx inject avrotize requests
```

**Comment by clemensv** [comment]
added to pyproject.toml. thank you!
